version: "3.9"

services:
  configurator:
    image: frappe/erpnext:v16
    pull_policy: ${PULL_POLICY:-always}
    #<<: [*depends_on_configurator, *customizable_image]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    platform: linux/amd64
    entrypoint:
      - bash
      - -c
    # add redis_socketio for backward compatibility
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      #DB_HOST: ${DB_HOST:-}
      #DB_PORT: ${DB_PORT:-}
      #REDIS_CACHE: ${REDIS_CACHE:-}
      #REDIS_QUEUE: ${REDIS_QUEUE:-}
      SOCKETIO_PORT: 9000
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - redis-cache
      - redis-queue
      - db
    restart: on-failure

  db:
    image: postgres:15
    #command: []
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-GMI464it}
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    image: frappe/erpnext:v16
    pull_policy: ${PULL_POLICY:-always}
    restart: ${RESTART_POLICY:-unless-stopped}
    depends_on:
      - configurator
    #<<: [*depends_on_configurator, *customizable_image]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    platform: linux/amd64

  frontend:
    image: frappe/erpnext:v16
    pull_policy: ${PULL_POLICY:-always}
    restart: ${RESTART_POLICY:-unless-stopped}
    platform: linux/amd64
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: ${FRAPPE_SITE_NAME_HEADER:-$$host}
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
      PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT:-120}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-50m}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      - backend
      - websocket

  websocket:
    # By default the image used only contains the `frappe` and `erpnext` apps.
    # See https://github.com/frappe/frappe_docker/blob/main/docs/container-setup/02-build-setup.md#define-custom-apps
    # about using custom images.
    image: frappe/erpnext:v16
    pull_policy: ${PULL_POLICY:-always}
    restart: ${RESTART_POLICY:-unless-stopped}
    depends_on:
      - configurator
    #<<: [*depends_on_configurator, *customizable_image]
    platform: linux/amd64
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  queue-short:
    image: frappe/erpnext:v16
    pull_policy: ${PULL_POLICY:-always}
    restart: ${RESTART_POLICY:-unless-stopped}
    depends_on:
      - configurator
    #<<: [*depends_on_configurator, *customizable_image]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    platform: linux/amd64
    command: bench worker --queue short,default

  queue-long:
    image: frappe/erpnext:v16
    pull_policy: ${PULL_POLICY:-always}
    restart: ${RESTART_POLICY:-unless-stopped}
    depends_on:
      - configurator
    #<<: [*depends_on_configurator, *customizable_image]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    platform: linux/amd64
    command: bench worker --queue long,default,short

  scheduler:
    image: frappe/erpnext:v16
    pull_policy: ${PULL_POLICY:-always}
    restart: ${RESTART_POLICY:-unless-stopped}
    depends_on:
      - configurator
    #<<: [*depends_on_configurator, *customizable_image]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    platform: linux/amd64
    command: bench schedule
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.datecron.schedule: "${BACKUP_CRONSTRING:-@every 6h}"
      ofelia.job-exec.datecron.command: "bench --site all backup"
      ofelia.job-exec.datecron.user: "frappe"

  redis-cache:
    image: redis:6.2-alpine
    restart: unless-stopped

  redis-queue:
    image: redis:6.2-alpine
    restart: unless-stopped
    volumes:
      - redis-queue-data:/data

  custom-domain:
    image: caddy:2
    command:
      - caddy
      - reverse-proxy
      - --to
      - frontend:8080
      - --from
      - :2016
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.erpnext.loadbalancer.server.port=2016
      - traefik.http.routers.erpnext.service=erpnext
      - traefik.http.routers.erpnext.entrypoints=http,https
      - traefik.http.routers.erpnext.tls=true
      - traefik.http.routers.erpnext.rule=Host(`erp.gmi.giize.com`)
      - traefik.http.middlewares.erpnext.headers.customrequestheaders.Host=erp.gmi.giize.com
      - traefik.http.routers.erpnext.middlewares=erpnext
    networks:
      - traefik-public
      - bench-network

  cron:
    image: mcuadros/ofelia:latest
    depends_on:
      - scheduler
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  web:
    external: true
  bench-network:
    name: ${BENCH_NETWORK:-bench-network}
    external: true

volumes:
  sites:
  redis-queue-data:
  db-data:
